import { randomUUID as uuidv4 } from 'crypto'

export const simulations = [
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Weekend Planning',
    description: 'Simulation to understand how friends plan weekend activities together',
    task: 'Analyze group decision-making patterns for weekend activities',
    created_at: '2024-07-20T10:00:00.000Z',
    updated_at: '2024-07-20T10:30:00.000Z',
    project_name: 'Friends Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Sarah',
        llm: { model: 'gpt-4o' },
        role: 'social organizer',
        description: 'Enthusiastic friend who loves planning group activities',
        backstory:
          'A 28-year-old marketing professional who thrives on bringing friends together. Known for her creativity and ability to find activities that everyone enjoys.',
      },
      {
        id: uuidv4(),
        name: 'Mike',
        llm: { model: 'gpt-4o' },
        role: 'practical planner',
        description: 'Logical friend who focuses on logistics and feasibility',
        backstory:
          "A 30-year-old engineer who approaches weekend planning with systematic thinking. He's the friend who checks weather forecasts and considers travel times.",
      },
      {
        id: uuidv4(),
        name: 'Emma',
        llm: { model: 'gpt-4o' },
        role: 'budget conscious friend',
        description: 'Cost-aware friend who suggests affordable alternatives',
        backstory:
          'A 26-year-old teacher who loves spending time with friends but is mindful of expenses.',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Vacation Planning',
    description: 'Simulation to understand how couples plan vacation activities together',
    task: 'Analyze couple decision-making patterns for vacation planning',
    created_at: '2024-07-20T11:00:00.000Z',
    updated_at: '2024-07-20T11:30:00.000Z',
    project_name: 'Couple Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Ana',
        llm: { model: 'gpt-4o' },
        role: 'adventure seeker',
        description: 'Enthusiastic partner who loves outdoor activities and mountain adventures',
        backstory:
          "A 29-year-old environmental scientist who finds peace in nature and loves challenging hikes. She's always looking for the next adventure and enjoys discovering new places.",
      },
      {
        id: uuidv4(),
        name: 'John',
        llm: { model: 'gpt-4o' },
        role: 'culture enthusiast',
        description: 'Partner who enjoys cultural experiences and city exploration',
        backstory:
          'A 31-year-old architect who appreciates both modern and historical architecture. He loves exploring cities, trying local cuisine, and experiencing different cultures through travel.',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Business Strategy',
    description: 'Simulation to understand how business teams make strategic decisions',
    task: 'Analyze team decision-making patterns for business strategy',
    created_at: '2024-07-20T12:00:00.000Z',
    updated_at: '2024-07-20T12:30:00.000Z',
    project_name: 'Business Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'CEO',
        llm: { model: 'gpt-4o' },
        role: 'strategic leader',
        description: 'Chief Executive Officer who makes final strategic decisions',
        backstory:
          'A 45-year-old experienced executive with 20+ years in the industry. Known for making bold decisions and leading companies through challenging times.',
      },
      {
        id: uuidv4(),
        name: 'CFO',
        llm: { model: 'gpt-4o' },
        role: 'financial advisor',
        description: 'Chief Financial Officer who provides financial analysis and advice',
        backstory:
          'A 42-year-old finance professional with strong analytical skills. Always considers the financial implications of strategic decisions.',
      },
      {
        id: uuidv4(),
        name: 'CTO',
        llm: { model: 'gpt-4o' },
        role: 'technology expert',
        description:
          'Chief Technology Officer who provides technology insights and recommendations',
        backstory:
          'A 38-year-old technology leader with expertise in emerging technologies. Focuses on how technology can drive business growth and innovation.',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Gym Buddy Motivation',
    description: 'Simulation to study how gym buddies influence each other\'s workout consistency',
    task: 'Analyze the impact of social support on fitness motivation',
    created_at: '2024-08-01T18:00:00.000Z',
    updated_at: '2024-08-01T18:40:00.000Z',
    project_name: 'Friends Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Alex',
        llm: { model: 'gpt-4o' },
        role: 'motivated gym buddy',
        description: 'Highly motivated fitness enthusiast who encourages their workout partner',
        backstory:
          'A 29-year-old software developer who discovered fitness three years ago and never looked back. Alex wakes up at 6 AM every day, has a detailed workout plan, and genuinely gets excited about helping others reach their fitness goals. They believe consistency is key and always shows up, even on tough days.',
      },
      {
        id: uuidv4(),
        name: 'Jordan',
        llm: { model: 'gpt-4o' },
        role: 'inconsistent gym buddy',
        description: 'Well-intentioned but struggling with workout consistency',
        backstory:
          'A 27-year-old graphic designer who wants to be fit but struggles with motivation and consistency. Jordan has good intentions and enjoys working out when they get started, but often finds excuses to skip sessions. They rely heavily on Alex\'s encouragement and feel guilty when they let their gym buddy down.',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Green Energy Adoption Rates',
    description: 'Simulation to analyze factors affecting green energy adoption',
    task: 'Study the impact of various factors on renewable energy adoption',
    created_at: '2024-04-20T08:00:00.000Z',
    updated_at: '2024-04-20T14:00:00.000Z',
    project_name: 'Climate Change Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Market Analyst',
        llm: { model: 'gpt-4o' },
        role: 'market analyst',
        description: 'Analyzes market conditions and consumer behavior',
        backstory: 'Expert in energy markets and consumer adoption patterns',
      },
      {
        id: uuidv4(),
        name: 'Policy Impact Specialist',
        llm: { model: 'gpt-4o' },
        role: 'policy specialist',
        description: 'Evaluates impact of policies on adoption rates',
        backstory: 'Specializes in energy policy analysis and implementation',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Influencer vs. Traditional Ads',
    description: 'Simulation to compare the effectiveness of influencer marketing versus traditional advertising',
    task: 'Analyze the impact of different marketing approaches on consumer behavior',
    created_at: '2024-05-10T10:00:00.000Z',
    updated_at: '2024-05-10T15:00:00.000Z',
    project_name: 'Marketing Campaign Effectiveness',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Influencer Specialist',
        llm: { model: 'gpt-4o' },
        role: 'influencer specialist',
        description: 'Designs influencer campaigns',
        backstory: 'Expert in social media marketing',
      },
      {
        id: uuidv4(),
        name: 'Traditional Ads Specialist',
        llm: { model: 'gpt-4o' },
        role: 'ads specialist',
        description: 'Designs traditional ad campaigns',
        backstory: 'Experienced in TV and print advertising',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Coalition Building and Policy Trade-offs',
    description: 'Simulation to analyze how political coalitions form and make policy decisions',
    task: 'Study the dynamics of coalition formation and policy negotiation',
    created_at: '2024-06-15T09:00:00.000Z',
    updated_at: '2024-06-15T14:00:00.000Z',
    project_name: 'Political Negotiation',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Party Leader',
        llm: { model: 'gpt-4o' },
        role: 'party leader',
        description: 'Leads a political party',
        backstory: 'Experienced negotiator',
      },
      {
        id: uuidv4(),
        name: 'Policy Analyst',
        llm: { model: 'gpt-4o' },
        role: 'policy analyst',
        description: 'Analyzes policy trade-offs',
        backstory: 'Expert in public policy',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Product Launch Timing',
    description: 'Simulation to determine optimal timing for launching a new product.',
    task: 'Analyze market conditions and competitor actions to select launch date.',
    created_at: '2024-09-10T11:00:00.000Z',
    updated_at: '2024-09-10T18:00:00.000Z',
    project_name: 'Startup Decision Making',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Market Analyst',
        llm: { model: 'gpt-4o' },
        role: 'market analyst',
        description: 'Analyzes market trends',
        backstory: 'Expert in product launches',
      },
      {
        id: uuidv4(),
        name: 'Competitor Analyst',
        llm: { model: 'gpt-4o' },
        role: 'competitor analyst',
        description: 'Tracks competitor activities',
        backstory: 'Experienced in competitive analysis',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Breaking Social Media Addiction',
    description: 'Simulation to study methods for overcoming social media addiction',
    task: 'Analyze the effectiveness of different addiction intervention strategies',
    created_at: '2024-05-25T11:00:00.000Z',
    updated_at: '2024-05-25T17:00:00.000Z',
    project_name: 'Digital Addiction',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Maya Patel',
        llm: { model: 'gpt-4o' },
        role: 'recovering user',
        description: 'A person actively working to reduce their social media usage and break addictive patterns',
        backstory:
          'A 26-year-old marketing professional who realized her Instagram and TikTok use was affecting her sleep, work focus, and real-world relationships',
      },
      {
        id: uuidv4(),
        name: 'Jake Anderson',
        llm: { model: 'gpt-4o' },
        role: 'supportive friend',
        description: 'A friend who provides accountability and alternative activities for someone reducing social media use',
        backstory:
          'A 28-year-old outdoor enthusiast who successfully reduced his own social media use and now helps friends find offline activities and hobbies',
      },
    ],
  },
,
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Remote vs Office Productivity',
    description: 'Simulation comparing productivity patterns between remote and office work environments',
    task: 'Analyze how different work environments affect team productivity and collaboration',
    created_at: '2024-08-05T09:00:00.000Z',
    updated_at: '2024-08-05T16:00:00.000Z',
    project_name: 'Work Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Remote Worker',
        llm: { model: 'gpt-4o' },
        role: 'remote employee',
        description: 'Employee working from home with flexible schedule',
        backstory: 'Software developer who transitioned to full remote work, enjoys the flexibility but sometimes misses office interactions',
      },
      {
        id: uuidv4(),
        name: 'Office Worker',
        llm: { model: 'gpt-4o' },
        role: 'office employee',
        description: 'Employee working from corporate office',
        backstory: 'Project manager who thrives on in-person collaboration and spontaneous discussions',
      },
      {
        id: uuidv4(),
        name: 'Hybrid Worker',
        llm: { model: 'gpt-4o' },
        role: 'hybrid employee',
        description: 'Employee splitting time between home and office',
        backstory: 'Marketing specialist who balances focused work at home with collaborative days in office',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Meeting Culture Impact',
    description: 'Simulation analyzing the impact of meeting frequency and format on productivity',
    task: 'Study how different meeting cultures affect team effectiveness and morale',
    created_at: '2024-08-06T10:00:00.000Z',
    updated_at: '2024-08-06T15:00:00.000Z',
    project_name: 'Work Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Meeting Minimalist',
        llm: { model: 'gpt-4o' },
        role: 'efficiency advocate',
        description: 'Advocates for fewer, more focused meetings',
        backstory: 'Senior developer who believes most meetings could be emails',
      },
      {
        id: uuidv4(),
        name: 'Collaboration Champion',
        llm: { model: 'gpt-4o' },
        role: 'meeting facilitator',
        description: 'Believes regular meetings drive alignment and innovation',
        backstory: 'Product owner who uses meetings to build consensus and drive decisions',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Burnout Prevention Strategies',
    description: 'Simulation exploring various approaches to prevent and manage workplace burnout',
    task: 'Analyze effectiveness of different burnout prevention strategies',
    created_at: '2024-08-07T08:00:00.000Z',
    updated_at: '2024-08-07T14:00:00.000Z',
    project_name: 'Work Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Overworked Employee',
        llm: { model: 'gpt-4o' },
        role: 'stressed employee',
        description: 'Employee experiencing signs of burnout',
        backstory: 'Marketing manager working 60+ hour weeks, struggling with work-life balance',
      },
      {
        id: uuidv4(),
        name: 'HR Specialist',
        llm: { model: 'gpt-4o' },
        role: 'wellness advocate',
        description: 'HR professional implementing wellness programs',
        backstory: 'Certified wellness coach focused on employee mental health and productivity',
      },
      {
        id: uuidv4(),
        name: 'Team Lead',
        llm: { model: 'gpt-4o' },
        role: 'supportive manager',
        description: 'Manager balancing team productivity with wellbeing',
        backstory: 'Engineering manager who learned importance of sustainable pace after own burnout experience',
      },
    ],
  },

  {
    id: uuidv4(),
    status: 'verified',
    name: 'Cross-Functional Team Dynamics',
    description: 'Simulation of collaboration between different departments on a shared project',
    task: 'Analyze how cross-functional teams overcome silos and achieve common goals',
    created_at: '2024-07-15T09:00:00.000Z',
    updated_at: '2024-07-15T17:00:00.000Z',
    project_name: 'Workplace Collaboration',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Engineering Lead',
        llm: { model: 'gpt-4o' },
        role: 'technical lead',
        description: 'Leads engineering team with focus on technical excellence',
        backstory: 'Senior engineer with 15 years experience, values clean code and scalability',
      },
      {
        id: uuidv4(),
        name: 'Marketing Lead',
        llm: { model: 'gpt-4o' },
        role: 'marketing strategist',
        description: 'Drives marketing initiatives and customer engagement',
        backstory: 'Creative director with strong brand vision and customer focus',
      },
      {
        id: uuidv4(),
        name: 'Sales Lead',
        llm: { model: 'gpt-4o' },
        role: 'sales director',
        description: 'Focuses on revenue generation and customer relationships',
        backstory: 'Top performer who understands customer needs and market dynamics',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Leadership Style Impact',
    description: 'Simulation comparing different leadership styles and their effects on team performance',
    task: 'Evaluate how various leadership approaches affect team collaboration and outcomes',
    created_at: '2024-07-16T10:00:00.000Z',
    updated_at: '2024-07-16T16:00:00.000Z',
    project_name: 'Workplace Collaboration',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Democratic Leader',
        llm: { model: 'gpt-4o' },
        role: 'collaborative leader',
        description: 'Leader who involves team in decision-making',
        backstory: 'Believes in collective wisdom and team empowerment',
      },
      {
        id: uuidv4(),
        name: 'Autocratic Leader',
        llm: { model: 'gpt-4o' },
        role: 'directive leader',
        description: 'Leader who makes quick, decisive decisions',
        backstory: 'Former military officer who values clear chain of command',
      },
      {
        id: uuidv4(),
        name: 'Servant Leader',
        llm: { model: 'gpt-4o' },
        role: 'supportive leader',
        description: 'Leader focused on serving and developing team members',
        backstory: 'Mentorship-focused leader who prioritizes team growth',
      },
    ],
  },

  {
    id: uuidv4(),
    status: 'verified',
    name: 'Just-In-Time vs Buffer Stock',
    description: 'Simulation comparing JIT and buffer stock strategies in supply chain management',
    task: 'Analyze trade-offs between inventory costs and supply chain resilience',
    created_at: '2024-06-20T08:00:00.000Z',
    updated_at: '2024-06-20T18:00:00.000Z',
    project_name: 'Supply Chain Optimization',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'JIT Advocate',
        llm: { model: 'gpt-4o' },
        role: 'lean specialist',
        description: 'Promotes just-in-time inventory management',
        backstory: 'Supply chain expert trained in Toyota Production System',
      },
      {
        id: uuidv4(),
        name: 'Risk Manager',
        llm: { model: 'gpt-4o' },
        role: 'risk analyst',
        description: 'Focuses on supply chain resilience and risk mitigation',
        backstory: 'Experienced manager who navigated multiple supply chain crises',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Vendor Selection Process',
    description: 'Simulation of multi-criteria vendor selection and negotiation',
    task: 'Optimize vendor selection considering cost, quality, reliability, and sustainability',
    created_at: '2024-06-21T09:00:00.000Z',
    updated_at: '2024-06-21T15:00:00.000Z',
    project_name: 'Supply Chain Optimization',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Procurement Manager',
        llm: { model: 'gpt-4o' },
        role: 'procurement lead',
        description: 'Manages vendor relationships and negotiations',
        backstory: 'Expert negotiator with 20 years in strategic sourcing',
      },
      {
        id: uuidv4(),
        name: 'Quality Auditor',
        llm: { model: 'gpt-4o' },
        role: 'quality specialist',
        description: 'Ensures vendor quality standards',
        backstory: 'Six Sigma black belt focused on zero defects',
      },
      {
        id: uuidv4(),
        name: 'Sustainability Officer',
        llm: { model: 'gpt-4o' },
        role: 'ESG advocate',
        description: 'Evaluates environmental and social governance factors',
        backstory: 'Passionate about sustainable and ethical sourcing',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Last Mile Delivery Optimization',
    description: 'Simulation optimizing last mile delivery strategies in urban environments',
    task: 'Balance delivery speed, cost, and customer satisfaction in last mile logistics',
    created_at: '2024-06-22T10:00:00.000Z',
    updated_at: '2024-06-22T17:00:00.000Z',
    project_name: 'Supply Chain Optimization',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Logistics Coordinator',
        llm: { model: 'gpt-4o' },
        role: 'route optimizer',
        description: 'Optimizes delivery routes and schedules',
        backstory: 'Operations expert specializing in urban logistics',
      },
      {
        id: uuidv4(),
        name: 'Customer Experience Manager',
        llm: { model: 'gpt-4o' },
        role: 'CX advocate',
        description: 'Focuses on delivery experience and customer satisfaction',
        backstory: 'Customer-obsessed manager who tracks every delivery metric',
      },
    ],
  },

  {
    id: uuidv4(),
    status: 'verified',
    name: 'Chatbot vs Human Support',
    description: 'Simulation comparing AI chatbot and human agent effectiveness in customer support',
    task: 'Analyze optimal balance between automated and human customer service',
    created_at: '2024-05-30T09:00:00.000Z',
    updated_at: '2024-05-30T16:00:00.000Z',
    project_name: 'Customer Service Optimization',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'AI Chatbot',
        llm: { model: 'gpt-4o' },
        role: 'automated support',
        description: 'AI-powered customer service chatbot',
        backstory: 'Advanced AI trained on millions of customer interactions',
      },
      {
        id: uuidv4(),
        name: 'Human Agent',
        llm: { model: 'gpt-4o' },
        role: 'empathetic support',
        description: 'Experienced human customer service representative',
        backstory: 'Senior agent with deep product knowledge and emotional intelligence',
      },
      {
        id: uuidv4(),
        name: 'Frustrated Customer',
        llm: { model: 'gpt-4o' },
        role: 'complex case',
        description: 'Customer with complex technical issue',
        backstory: 'Long-time customer experiencing recurring problem, needs empathy and solution',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Escalation Path Optimization',
    description: 'Simulation of customer issue escalation procedures and resolution times',
    task: 'Optimize escalation paths to minimize resolution time and maximize satisfaction',
    created_at: '2024-05-31T10:00:00.000Z',
    updated_at: '2024-05-31T15:00:00.000Z',
    project_name: 'Customer Service Optimization',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Tier 1 Support',
        llm: { model: 'gpt-4o' },
        role: 'first responder',
        description: 'Initial customer contact point',
        backstory: 'New agent learning to identify escalation triggers',
      },
      {
        id: uuidv4(),
        name: 'Tier 2 Support',
        llm: { model: 'gpt-4o' },
        role: 'technical specialist',
        description: 'Handles complex technical issues',
        backstory: 'Technical expert with deep product knowledge',
      },
      {
        id: uuidv4(),
        name: 'Support Manager',
        llm: { model: 'gpt-4o' },
        role: 'escalation handler',
        description: 'Manages high-priority escalations',
        backstory: 'Experienced manager who can authorize special resolutions',
      },
    ],
  },

  {
    id: uuidv4(),
    status: 'verified',
    name: 'Go-To-Market Coordination',
    description: 'Simulation of cross-functional product launch coordination',
    task: 'Align marketing, sales, and product teams for successful launch',
    created_at: '2024-09-01T09:00:00.000Z',
    updated_at: '2024-09-01T18:00:00.000Z',
    project_name: 'Product Launch Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Product Manager',
        llm: { model: 'gpt-4o' },
        role: 'launch coordinator',
        description: 'Coordinates all aspects of product launch',
        backstory: 'Experienced PM who has launched multiple successful products',
      },
      {
        id: uuidv4(),
        name: 'Marketing Director',
        llm: { model: 'gpt-4o' },
        role: 'brand strategist',
        description: 'Develops launch messaging and campaigns',
        backstory: 'Creative strategist with track record of viral campaigns',
      },
      {
        id: uuidv4(),
        name: 'Sales Director',
        llm: { model: 'gpt-4o' },
        role: 'revenue driver',
        description: 'Prepares sales team and channel partners',
        backstory: 'Sales leader focused on hitting launch targets',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Beta Testing Strategy',
    description: 'Simulation of beta testing program design and feedback integration',
    task: 'Optimize beta testing to improve product quality before launch',
    created_at: '2024-09-02T10:00:00.000Z',
    updated_at: '2024-09-02T16:00:00.000Z',
    project_name: 'Product Launch Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Beta Program Manager',
        llm: { model: 'gpt-4o' },
        role: 'beta coordinator',
        description: 'Manages beta testing program',
        backstory: 'Expert in user testing and feedback analysis',
      },
      {
        id: uuidv4(),
        name: 'Power User',
        llm: { model: 'gpt-4o' },
        role: 'beta tester',
        description: 'Experienced beta tester providing detailed feedback',
        backstory: 'Tech enthusiast who loves finding edge cases',
      },
      {
        id: uuidv4(),
        name: 'Engineering Lead',
        llm: { model: 'gpt-4o' },
        role: 'bug fixer',
        description: 'Prioritizes and fixes issues from beta feedback',
        backstory: 'Senior engineer committed to product quality',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Launch Pricing Strategy',
    description: 'Simulation of pricing strategy development for new product launch',
    task: 'Determine optimal pricing strategy balancing adoption and revenue',
    created_at: '2024-09-03T11:00:00.000Z',
    updated_at: '2024-09-03T17:00:00.000Z',
    project_name: 'Product Launch Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Pricing Analyst',
        llm: { model: 'gpt-4o' },
        role: 'pricing strategist',
        description: 'Develops data-driven pricing models',
        backstory: 'Economics PhD with expertise in price elasticity',
      },
      {
        id: uuidv4(),
        name: 'Competitive Analyst',
        llm: { model: 'gpt-4o' },
        role: 'market researcher',
        description: 'Analyzes competitor pricing and positioning',
        backstory: 'Former consultant specializing in competitive intelligence',
      },
    ],
  },

  {
    id: uuidv4(),
    status: 'verified',
    name: 'Data Breach Response',
    description: 'Simulation of organizational response to a major data breach',
    task: 'Coordinate crisis response across legal, PR, IT, and customer service teams',
    created_at: '2024-10-01T03:00:00.000Z',
    updated_at: '2024-10-01T20:00:00.000Z',
    project_name: 'Crisis Management Response',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Crisis Manager',
        llm: { model: 'gpt-4o' },
        role: 'incident commander',
        description: 'Coordinates overall crisis response',
        backstory: 'Former military officer with extensive crisis management experience',
      },
      {
        id: uuidv4(),
        name: 'CISO',
        llm: { model: 'gpt-4o' },
        role: 'security lead',
        description: 'Manages technical response and forensics',
        backstory: 'Cybersecurity expert who has handled multiple breaches',
      },
      {
        id: uuidv4(),
        name: 'PR Director',
        llm: { model: 'gpt-4o' },
        role: 'communications lead',
        description: 'Manages external communications and reputation',
        backstory: 'Crisis communications specialist with media relationships',
      },
      {
        id: uuidv4(),
        name: 'Legal Counsel',
        llm: { model: 'gpt-4o' },
        role: 'compliance advisor',
        description: 'Ensures regulatory compliance and manages legal risks',
        backstory: 'Privacy law expert familiar with GDPR and breach notifications',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Product Recall Management',
    description: 'Simulation of product recall crisis management and coordination',
    task: 'Manage product recall while maintaining customer trust and brand reputation',
    created_at: '2024-10-02T08:00:00.000Z',
    updated_at: '2024-10-02T18:00:00.000Z',
    project_name: 'Crisis Management Response',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Quality Director',
        llm: { model: 'gpt-4o' },
        role: 'quality lead',
        description: 'Identifies scope and severity of product issues',
        backstory: 'Quality expert who discovered the defect during routine testing',
      },
      {
        id: uuidv4(),
        name: 'Operations Manager',
        llm: { model: 'gpt-4o' },
        role: 'logistics coordinator',
        description: 'Manages recall logistics and replacement products',
        backstory: 'Supply chain expert handling reverse logistics',
      },
      {
        id: uuidv4(),
        name: 'Customer Relations Head',
        llm: { model: 'gpt-4o' },
        role: 'customer advocate',
        description: 'Manages customer communications and satisfaction',
        backstory: 'Customer experience leader focused on retention during crisis',
      },
    ],
  },

  {
    id: uuidv4(),
    status: 'verified',
    name: 'Cultural Integration Strategy',
    description: 'Simulation of merging two distinct company cultures',
    task: 'Develop strategies to integrate different organizational cultures post-merger',
    created_at: '2024-11-01T09:00:00.000Z',
    updated_at: '2024-11-01T17:00:00.000Z',
    project_name: 'Merger Integration Planning',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Acquiring Company HR',
        llm: { model: 'gpt-4o' },
        role: 'culture champion',
        description: 'Represents acquiring company culture and values',
        backstory: 'HR leader from Fortune 500 with formal corporate culture',
      },
      {
        id: uuidv4(),
        name: 'Acquired Company HR',
        llm: { model: 'gpt-4o' },
        role: 'culture advocate',
        description: 'Protects acquired company culture and employee interests',
        backstory: 'HR leader from startup with informal, innovative culture',
      },
      {
        id: uuidv4(),
        name: 'Integration Consultant',
        llm: { model: 'gpt-4o' },
        role: 'neutral mediator',
        description: 'External consultant facilitating cultural integration',
        backstory: 'M&A specialist who has guided 50+ successful integrations',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Systems Integration Planning',
    description: 'Simulation of IT systems integration during merger',
    task: 'Plan and execute integration of disparate IT systems and data',
    created_at: '2024-11-02T10:00:00.000Z',
    updated_at: '2024-11-02T18:00:00.000Z',
    project_name: 'Merger Integration Planning',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'CTO Company A',
        llm: { model: 'gpt-4o' },
        role: 'tech leader A',
        description: 'Advocates for Company A technology stack',
        backstory: 'Built current systems from ground up over 10 years',
      },
      {
        id: uuidv4(),
        name: 'CTO Company B',
        llm: { model: 'gpt-4o' },
        role: 'tech leader B',
        description: 'Advocates for Company B technology approach',
        backstory: 'Modernized legacy systems with cloud-native architecture',
      },
      {
        id: uuidv4(),
        name: 'Data Architect',
        llm: { model: 'gpt-4o' },
        role: 'integration specialist',
        description: 'Designs unified data architecture',
        backstory: 'Expert in data migration and system consolidation',
      },
    ],
  },

  {
    id: uuidv4(),
    status: 'verified',
    name: 'Annual Budget Negotiations',
    description: 'Simulation of department heads negotiating annual budget allocations',
    task: 'Balance competing departmental needs within constrained budget',
    created_at: '2024-12-01T09:00:00.000Z',
    updated_at: '2024-12-01T18:00:00.000Z',
    project_name: 'Budget Allocation Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'R&D Director',
        llm: { model: 'gpt-4o' },
        role: 'innovation advocate',
        description: 'Argues for increased R&D investment',
        backstory: 'Believes innovation drives long-term competitive advantage',
      },
      {
        id: uuidv4(),
        name: 'Sales VP',
        llm: { model: 'gpt-4o' },
        role: 'revenue focus',
        description: 'Pushes for sales and marketing budget',
        backstory: 'Needs resources to hit aggressive growth targets',
      },
      {
        id: uuidv4(),
        name: 'CFO',
        llm: { model: 'gpt-4o' },
        role: 'financial gatekeeper',
        description: 'Ensures fiscal responsibility and ROI',
        backstory: 'Conservative financial leader focused on profitability',
      },
      {
        id: uuidv4(),
        name: 'Operations Head',
        llm: { model: 'gpt-4o' },
        role: 'efficiency driver',
        description: 'Seeks budget for operational improvements',
        backstory: 'Wants to modernize aging infrastructure',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Emergency Budget Reallocation',
    description: 'Simulation of rapid budget reallocation during economic downturn',
    task: 'Quickly adjust budgets to respond to 30% revenue shortfall',
    created_at: '2024-12-02T14:00:00.000Z',
    updated_at: '2024-12-02T20:00:00.000Z',
    project_name: 'Budget Allocation Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'CEO',
        llm: { model: 'gpt-4o' },
        role: 'strategic decision maker',
        description: 'Makes final decisions on budget cuts',
        backstory: 'Experienced leader who has navigated multiple downturns',
      },
      {
        id: uuidv4(),
        name: 'HR Director',
        llm: { model: 'gpt-4o' },
        role: 'people advocate',
        description: 'Tries to minimize layoffs and protect talent',
        backstory: 'Believes employees are the companys greatest asset',
      },
      {
        id: uuidv4(),
        name: 'Board Representative',
        llm: { model: 'gpt-4o' },
        role: 'shareholder voice',
        description: 'Represents board and shareholder interests',
        backstory: 'Private equity partner focused on maintaining valuation',
      },
    ],
  },

  {
    id: uuidv4(),
    status: 'verified',
    name: 'Tech Talent Competition',
    description: 'Simulation of competing for top software engineering talent',
    task: 'Win top talent in competitive market with multiple offers',
    created_at: '2024-03-15T10:00:00.000Z',
    updated_at: '2024-03-15T16:00:00.000Z',
    project_name: 'Talent Acquisition Pipeline',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Startup Recruiter',
        llm: { model: 'gpt-4o' },
        role: 'startup advocate',
        description: 'Sells equity upside and impact opportunity',
        backstory: 'Former engineer who joined early startup and made fortune',
      },
      {
        id: uuidv4(),
        name: 'Big Tech Recruiter',
        llm: { model: 'gpt-4o' },
        role: 'corporate recruiter',
        description: 'Offers stability, benefits, and brand prestige',
        backstory: 'Veteran recruiter from FAANG company with unlimited budget',
      },
      {
        id: uuidv4(),
        name: 'Top Candidate',
        llm: { model: 'gpt-4o' },
        role: 'senior engineer',
        description: 'Highly sought-after ML engineer with multiple offers',
        backstory: 'Stanford PhD with successful open source projects',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Diversity Hiring Initiative',
    description: 'Simulation of implementing diversity-focused recruitment strategy',
    task: 'Build diverse talent pipeline while maintaining merit-based selection',
    created_at: '2024-03-16T09:00:00.000Z',
    updated_at: '2024-03-16T15:00:00.000Z',
    project_name: 'Talent Acquisition Pipeline',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'DEI Leader',
        llm: { model: 'gpt-4o' },
        role: 'diversity advocate',
        description: 'Champions inclusive hiring practices',
        backstory: 'Former consultant specializing in organizational diversity',
      },
      {
        id: uuidv4(),
        name: 'Hiring Manager',
        llm: { model: 'gpt-4o' },
        role: 'team builder',
        description: 'Seeks best talent for technical team',
        backstory: 'Engineering manager focused on team performance',
      },
      {
        id: uuidv4(),
        name: 'Talent Scout',
        llm: { model: 'gpt-4o' },
        role: 'pipeline builder',
        description: 'Sources candidates from diverse backgrounds',
        backstory: 'Recruiter with strong networks in underrepresented communities',
      },
    ],
  },

  // Retail Store Network Planning simulations (2)
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Urban vs Suburban Expansion',
    description: 'Simulation comparing urban and suburban retail expansion strategies',
    task: 'Determine optimal location strategy for retail network growth',
    created_at: '2024-04-10T09:00:00.000Z',
    updated_at: '2024-04-10T17:00:00.000Z',
    project_name: 'Retail Store Network Planning',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Urban Strategist',
        llm: { model: 'gpt-4o' },
        role: 'city advocate',
        description: 'Advocates for high-density urban locations',
        backstory: 'Real estate expert specializing in metropolitan markets',
      },
      {
        id: uuidv4(),
        name: 'Suburban Strategist',
        llm: { model: 'gpt-4o' },
        role: 'suburban advocate',
        description: 'Promotes suburban expansion with larger formats',
        backstory: 'Former mall developer who understands suburban shoppers',
      },
      {
        id: uuidv4(),
        name: 'Data Analyst',
        llm: { model: 'gpt-4o' },
        role: 'location intelligence',
        description: 'Provides demographic and traffic analysis',
        backstory: 'GIS specialist with retail analytics expertise',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Omnichannel Inventory Distribution',
    description: 'Simulation of inventory allocation across stores and fulfillment centers',
    task: 'Optimize inventory placement for omnichannel retail operations',
    created_at: '2024-04-11T10:00:00.000Z',
    updated_at: '2024-04-11T16:00:00.000Z',
    project_name: 'Retail Store Network Planning',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'E-commerce Manager',
        llm: { model: 'gpt-4o' },
        role: 'online fulfillment',
        description: 'Optimizes for fast online delivery',
        backstory: 'Former Amazon operations manager',
      },
      {
        id: uuidv4(),
        name: 'Store Operations Director',
        llm: { model: 'gpt-4o' },
        role: 'store advocate',
        description: 'Ensures stores have adequate inventory',
        backstory: '20-year retail veteran managing 100+ stores',
      },
    ],
  },

  // Healthcare Resource Management simulations (3)
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Emergency Department Optimization',
    description: 'Simulation of ED patient flow and resource allocation',
    task: 'Reduce wait times while maintaining quality of care',
    created_at: '2024-02-20T06:00:00.000Z',
    updated_at: '2024-02-20T18:00:00.000Z',
    project_name: 'Healthcare Resource Management',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'ED Director',
        llm: { model: 'gpt-4o' },
        role: 'department head',
        description: 'Manages emergency department operations',
        backstory: 'Emergency physician with 15 years experience',
      },
      {
        id: uuidv4(),
        name: 'Triage Nurse',
        llm: { model: 'gpt-4o' },
        role: 'patient prioritization',
        description: 'Assesses and prioritizes incoming patients',
        backstory: 'Veteran nurse with excellent clinical judgment',
      },
      {
        id: uuidv4(),
        name: 'Resource Coordinator',
        llm: { model: 'gpt-4o' },
        role: 'resource manager',
        description: 'Allocates beds, staff, and equipment',
        backstory: 'Operations expert focused on throughput optimization',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Surgery Schedule Optimization',
    description: 'Simulation of OR scheduling and resource utilization',
    task: 'Maximize OR utilization while minimizing overtime and delays',
    created_at: '2024-02-21T07:00:00.000Z',
    updated_at: '2024-02-21T15:00:00.000Z',
    project_name: 'Healthcare Resource Management',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'OR Scheduler',
        llm: { model: 'gpt-4o' },
        role: 'schedule coordinator',
        description: 'Creates and manages surgery schedules',
        backstory: 'Expert in balancing surgeon preferences with efficiency',
      },
      {
        id: uuidv4(),
        name: 'Chief Surgeon',
        llm: { model: 'gpt-4o' },
        role: 'surgical leader',
        description: 'Advocates for surgical team needs',
        backstory: 'Department head balancing quality and efficiency',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Nursing Staff Allocation',
    description: 'Simulation of nurse scheduling across hospital units',
    task: 'Optimize nurse-to-patient ratios while managing costs',
    created_at: '2024-02-22T08:00:00.000Z',
    updated_at: '2024-02-22T14:00:00.000Z',
    project_name: 'Healthcare Resource Management',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Chief Nursing Officer',
        llm: { model: 'gpt-4o' },
        role: 'nursing executive',
        description: 'Oversees nursing operations and staffing',
        backstory: 'Nurse leader focused on patient safety and staff wellbeing',
      },
      {
        id: uuidv4(),
        name: 'Unit Manager',
        llm: { model: 'gpt-4o' },
        role: 'unit coordinator',
        description: 'Manages specific hospital unit staffing',
        backstory: 'Experienced manager of high-acuity medical unit',
      },
      {
        id: uuidv4(),
        name: 'Float Pool Coordinator',
        llm: { model: 'gpt-4o' },
        role: 'flex staffing',
        description: 'Manages float pool nurses for coverage',
        backstory: 'Expert in matching skills to unit needs',
      },
    ],
  },

  // Contract Negotiation Dynamics simulations (2)
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Software Licensing Deal',
    description: 'Simulation of enterprise software licensing negotiation',
    task: 'Negotiate favorable terms balancing cost, features, and flexibility',
    created_at: '2024-01-20T10:00:00.000Z',
    updated_at: '2024-01-20T16:00:00.000Z',
    project_name: 'Contract Negotiation Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Software Vendor',
        llm: { model: 'gpt-4o' },
        role: 'sales executive',
        description: 'Maximizes deal value and lock-in',
        backstory: 'Enterprise sales rep with quarterly quota pressure',
      },
      {
        id: uuidv4(),
        name: 'Procurement Manager',
        llm: { model: 'gpt-4o' },
        role: 'buyer representative',
        description: 'Seeks best value and flexible terms',
        backstory: 'Former vendor who knows all the sales tactics',
      },
      {
        id: uuidv4(),
        name: 'Legal Advisor',
        llm: { model: 'gpt-4o' },
        role: 'contract specialist',
        description: 'Ensures favorable legal terms and protections',
        backstory: 'Corporate lawyer specializing in technology contracts',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Joint Venture Agreement',
    description: 'Simulation of joint venture partnership negotiation',
    task: 'Structure equitable partnership with aligned incentives',
    created_at: '2024-01-21T09:00:00.000Z',
    updated_at: '2024-01-21T18:00:00.000Z',
    project_name: 'Contract Negotiation Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Company A CEO',
        llm: { model: 'gpt-4o' },
        role: 'strategic partner',
        description: 'Brings technology and expertise',
        backstory: 'Tech company founder seeking market access',
      },
      {
        id: uuidv4(),
        name: 'Company B CEO',
        llm: { model: 'gpt-4o' },
        role: 'market partner',
        description: 'Provides distribution and customer base',
        backstory: 'Traditional industry leader seeking innovation',
      },
    ],
  },

  // Digital Transformation Roadmap simulations (3)
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Legacy System Modernization',
    description: 'Simulation of replacing legacy systems with modern architecture',
    task: 'Plan phased migration from mainframe to cloud-native systems',
    created_at: '2024-07-10T09:00:00.000Z',
    updated_at: '2024-07-10T17:00:00.000Z',
    project_name: 'Digital Transformation Roadmap',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Transformation Lead',
        llm: { model: 'gpt-4o' },
        role: 'change champion',
        description: 'Drives digital transformation initiative',
        backstory: 'Former consultant who led Fortune 100 transformations',
      },
      {
        id: uuidv4(),
        name: 'Legacy System Owner',
        llm: { model: 'gpt-4o' },
        role: 'system guardian',
        description: 'Maintains critical legacy systems',
        backstory: 'COBOL expert whos kept systems running for 20 years',
      },
      {
        id: uuidv4(),
        name: 'Cloud Architect',
        llm: { model: 'gpt-4o' },
        role: 'modernization expert',
        description: 'Designs cloud-native solutions',
        backstory: 'Former AWS engineer specializing in migrations',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Data Platform Modernization',
    description: 'Simulation of building modern data platform and analytics capabilities',
    task: 'Transform from siloed databases to unified data lake and real-time analytics',
    created_at: '2024-07-11T10:00:00.000Z',
    updated_at: '2024-07-11T16:00:00.000Z',
    project_name: 'Digital Transformation Roadmap',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Chief Data Officer',
        llm: { model: 'gpt-4o' },
        role: 'data strategist',
        description: 'Champions data-driven transformation',
        backstory: 'Built data platforms at multiple tech giants',
      },
      {
        id: uuidv4(),
        name: 'Business Analyst',
        llm: { model: 'gpt-4o' },
        role: 'requirements advocate',
        description: 'Represents business analytics needs',
        backstory: 'Power user frustrated with current data limitations',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Digital Customer Experience',
    description: 'Simulation of creating omnichannel digital customer experience',
    task: 'Design seamless customer journey across web, mobile, and physical touchpoints',
    created_at: '2024-07-12T11:00:00.000Z',
    updated_at: '2024-07-12T17:00:00.000Z',
    project_name: 'Digital Transformation Roadmap',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'CX Designer',
        llm: { model: 'gpt-4o' },
        role: 'experience architect',
        description: 'Designs customer journey and touchpoints',
        backstory: 'UX expert from leading digital agency',
      },
      {
        id: uuidv4(),
        name: 'Digital Product Manager',
        llm: { model: 'gpt-4o' },
        role: 'product owner',
        description: 'Manages digital product portfolio',
        backstory: 'Former startup founder focused on user engagement',
      },
      {
        id: uuidv4(),
        name: 'Channel Manager',
        llm: { model: 'gpt-4o' },
        role: 'omnichannel coordinator',
        description: 'Ensures consistency across channels',
        backstory: 'Retail veteran bridging physical and digital',
      },
    ],
  },

  // Competitive Pricing Strategy simulations (2)
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Price War Dynamics',
    description: 'Simulation of competitive pricing in commodity market',
    task: 'Navigate price competition while maintaining profitability',
    created_at: '2024-08-20T09:00:00.000Z',
    updated_at: '2024-08-20T15:00:00.000Z',
    project_name: 'Competitive Pricing Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Market Leader',
        llm: { model: 'gpt-4o' },
        role: 'incumbent',
        description: 'Defends market share with pricing power',
        backstory: 'Established player with 40% market share',
      },
      {
        id: uuidv4(),
        name: 'Challenger',
        llm: { model: 'gpt-4o' },
        role: 'disruptor',
        description: 'Aggressive pricing to gain market share',
        backstory: 'New entrant with venture backing and growth mandate',
      },
      {
        id: uuidv4(),
        name: 'Niche Player',
        llm: { model: 'gpt-4o' },
        role: 'specialist',
        description: 'Premium pricing for specialized segments',
        backstory: 'Boutique provider focusing on quality over volume',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Dynamic Pricing Algorithm',
    description: 'Simulation of AI-driven dynamic pricing strategies',
    task: 'Optimize pricing in real-time based on demand and competition',
    created_at: '2024-08-21T10:00:00.000Z',
    updated_at: '2024-08-21T16:00:00.000Z',
    project_name: 'Competitive Pricing Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Revenue Optimizer',
        llm: { model: 'gpt-4o' },
        role: 'algorithm designer',
        description: 'Develops pricing algorithms for revenue maximization',
        backstory: 'Data scientist from airline industry with yield management expertise',
      },
      {
        id: uuidv4(),
        name: 'Market Analyst',
        llm: { model: 'gpt-4o' },
        role: 'demand forecaster',
        description: 'Predicts demand patterns and elasticity',
        backstory: 'Economist specializing in consumer behavior',
      },
    ],
  },

  // Remote Team Coordination simulations (2)
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Global Team Handoffs',
    description: 'Simulation of 24/7 development with teams across time zones',
    task: 'Optimize handoffs and communication for continuous development',
    created_at: '2024-09-20T00:00:00.000Z',
    updated_at: '2024-09-20T23:59:00.000Z',
    project_name: 'Remote Team Coordination',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'US Team Lead',
        llm: { model: 'gpt-4o' },
        role: 'americas coordinator',
        description: 'Manages team in San Francisco timezone',
        backstory: 'Silicon Valley engineer managing distributed teams for 5 years',
      },
      {
        id: uuidv4(),
        name: 'EU Team Lead',
        llm: { model: 'gpt-4o' },
        role: 'europe coordinator',
        description: 'Manages team in London/Berlin timezones',
        backstory: 'European tech lead bridging US and Asia teams',
      },
      {
        id: uuidv4(),
        name: 'Asia Team Lead',
        llm: { model: 'gpt-4o' },
        role: 'asia coordinator',
        description: 'Manages team in Singapore/Tokyo timezones',
        backstory: 'Senior developer ensuring smooth handoffs across regions',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Virtual Team Building',
    description: 'Simulation of building team cohesion in fully remote environment',
    task: 'Foster team culture and collaboration without physical proximity',
    created_at: '2024-09-21T10:00:00.000Z',
    updated_at: '2024-09-21T16:00:00.000Z',
    project_name: 'Remote Team Coordination',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Remote Culture Manager',
        llm: { model: 'gpt-4o' },
        role: 'culture builder',
        description: 'Creates virtual team building initiatives',
        backstory: 'HR specialist who transitioned company to full remote',
      },
      {
        id: uuidv4(),
        name: 'Isolated Employee',
        llm: { model: 'gpt-4o' },
        role: 'remote worker',
        description: 'Struggling with isolation and disconnection',
        backstory: 'Junior developer missing office interactions and mentorship',
      },
      {
        id: uuidv4(),
        name: 'Team Advocate',
        llm: { model: 'gpt-4o' },
        role: 'engagement champion',
        description: 'Promotes team activities and connections',
        backstory: 'Remote work veteran who maintains strong team bonds',
      },
    ],
  },

  // Risk Assessment Framework simulations (2)
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Cybersecurity Risk Evaluation',
    description: 'Simulation of comprehensive cybersecurity risk assessment',
    task: 'Identify and prioritize cybersecurity risks across the enterprise',
    created_at: '2024-10-10T09:00:00.000Z',
    updated_at: '2024-10-10T17:00:00.000Z',
    project_name: 'Risk Assessment Framework',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Security Analyst',
        llm: { model: 'gpt-4o' },
        role: 'threat assessor',
        description: 'Identifies and analyzes security vulnerabilities',
        backstory: 'Former ethical hacker with deep security expertise',
      },
      {
        id: uuidv4(),
        name: 'Risk Manager',
        llm: { model: 'gpt-4o' },
        role: 'risk quantifier',
        description: 'Quantifies and prioritizes enterprise risks',
        backstory: 'CPA with expertise in risk modeling and compliance',
      },
      {
        id: uuidv4(),
        name: 'Business Stakeholder',
        llm: { model: 'gpt-4o' },
        role: 'business representative',
        description: 'Balances security with business operations',
        backstory: 'Operations executive focused on business continuity',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Supply Chain Risk Analysis',
    description: 'Simulation of supply chain vulnerability assessment',
    task: 'Map and mitigate risks across global supply chain',
    created_at: '2024-10-11T10:00:00.000Z',
    updated_at: '2024-10-11T16:00:00.000Z',
    project_name: 'Risk Assessment Framework',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Supply Chain Analyst',
        llm: { model: 'gpt-4o' },
        role: 'chain mapper',
        description: 'Maps supply chain dependencies and vulnerabilities',
        backstory: 'Logistics expert who navigated COVID supply disruptions',
      },
      {
        id: uuidv4(),
        name: 'Geopolitical Advisor',
        llm: { model: 'gpt-4o' },
        role: 'risk advisor',
        description: 'Assesses political and regulatory risks',
        backstory: 'Former diplomat with global trade expertise',
      },
    ],
  },

  // Startup Investment Evaluation simulations (3)
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Seed Round Negotiation',
    description: 'Simulation of seed investment terms negotiation',
    task: 'Structure seed round balancing founder control and investor protection',
    created_at: '2024-11-10T10:00:00.000Z',
    updated_at: '2024-11-10T18:00:00.000Z',
    project_name: 'Startup Investment Evaluation',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Startup Founder',
        llm: { model: 'gpt-4o' },
        role: 'entrepreneur',
        description: 'Seeks funding while maintaining control',
        backstory: 'Technical founder with breakthrough AI technology',
      },
      {
        id: uuidv4(),
        name: 'Angel Investor',
        llm: { model: 'gpt-4o' },
        role: 'early investor',
        description: 'Provides capital and mentorship',
        backstory: 'Successful entrepreneur turned angel investor',
      },
      {
        id: uuidv4(),
        name: 'VC Partner',
        llm: { model: 'gpt-4o' },
        role: 'institutional investor',
        description: 'Represents venture fund interests',
        backstory: 'Partner at top-tier VC with board experience',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Due Diligence Process',
    description: 'Simulation of comprehensive startup due diligence',
    task: 'Evaluate startup viability through multi-faceted due diligence',
    created_at: '2024-11-11T09:00:00.000Z',
    updated_at: '2024-11-11T17:00:00.000Z',
    project_name: 'Startup Investment Evaluation',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Technical Auditor',
        llm: { model: 'gpt-4o' },
        role: 'tech evaluator',
        description: 'Assesses technology and IP strength',
        backstory: 'Former CTO who evaluates deep tech startups',
      },
      {
        id: uuidv4(),
        name: 'Market Analyst',
        llm: { model: 'gpt-4o' },
        role: 'market validator',
        description: 'Evaluates market size and competition',
        backstory: 'Strategy consultant specializing in market entry',
      },
      {
        id: uuidv4(),
        name: 'Financial Analyst',
        llm: { model: 'gpt-4o' },
        role: 'numbers validator',
        description: 'Reviews financials and unit economics',
        backstory: 'Former investment banker focused on SaaS metrics',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Exit Strategy Planning',
    description: 'Simulation of startup exit strategy evaluation',
    task: 'Evaluate acquisition vs IPO vs continued growth options',
    created_at: '2024-11-12T10:00:00.000Z',
    updated_at: '2024-11-12T16:00:00.000Z',
    project_name: 'Startup Investment Evaluation',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Founder CEO',
        llm: { model: 'gpt-4o' },
        role: 'vision holder',
        description: 'Balances growth ambitions with exit pressure',
        backstory: 'Serial entrepreneur considering various exit paths',
      },
      {
        id: uuidv4(),
        name: 'Lead Investor',
        llm: { model: 'gpt-4o' },
        role: 'board member',
        description: 'Seeks optimal return on investment',
        backstory: 'VC partner with fund returning pressure',
      },
      {
        id: uuidv4(),
        name: 'Strategic Acquirer',
        llm: { model: 'gpt-4o' },
        role: 'potential buyer',
        description: 'Evaluates acquisition opportunity',
        backstory: 'Corp dev executive from Fortune 500 tech company',
      },
    ],
  },

  // Additional simulations for projects with room for more
  
  // Friends Dynamics additional simulations (up to 5 total)
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Group Travel Planning',
    description: 'Simulation of friends planning an international trip together',
    task: 'Analyze how different personalities and preferences affect group travel decisions',
    created_at: '2024-07-21T09:00:00.000Z',
    updated_at: '2024-07-21T15:00:00.000Z',
    project_name: 'Friends Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Adventure Seeker',
        llm: { model: 'gpt-4o' },
        role: 'thrill enthusiast',
        description: 'Wants extreme activities and off-beaten paths',
        backstory: 'Travel blogger who loves adrenaline-pumping experiences',
      },
      {
        id: uuidv4(),
        name: 'Comfort Traveler',
        llm: { model: 'gpt-4o' },
        role: 'luxury preferrer',
        description: 'Prefers comfortable accommodations and planned itineraries',
        backstory: 'Corporate executive who values relaxation on vacation',
      },
      {
        id: uuidv4(),
        name: 'Budget Backpacker',
        llm: { model: 'gpt-4o' },
        role: 'frugal explorer',
        description: 'Focuses on authentic experiences within tight budget',
        backstory: 'Graduate student who has traveled to 30 countries on a shoestring',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Roommate Conflict Resolution',
    description: 'Simulation of friends navigating roommate conflicts',
    task: 'Study conflict resolution strategies in shared living situations',
    created_at: '2024-07-22T10:00:00.000Z',
    updated_at: '2024-07-22T14:00:00.000Z',
    project_name: 'Friends Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Clean Freak',
        llm: { model: 'gpt-4o' },
        role: 'neat roommate',
        description: 'Obsessed with cleanliness and organization',
        backstory: 'Medical student who believes cleanliness affects productivity',
      },
      {
        id: uuidv4(),
        name: 'Party Host',
        llm: { model: 'gpt-4o' },
        role: 'social roommate',
        description: 'Loves hosting gatherings and social events',
        backstory: 'Event planner who sees home as social hub',
      },
      {
        id: uuidv4(),
        name: 'Quiet Introvert',
        llm: { model: 'gpt-4o' },
        role: 'private roommate',
        description: 'Values peace, quiet, and personal space',
        backstory: 'Remote worker who needs quiet environment for focus',
      },
    ],
  },

  // Climate Change Strategy additional simulations (up to 5 total)
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Carbon Tax Implementation',
    description: 'Simulation of implementing carbon tax across different industries',
    task: 'Analyze impact of carbon pricing on business behavior and emissions',
    created_at: '2024-04-21T09:00:00.000Z',
    updated_at: '2024-04-21T16:00:00.000Z',
    project_name: 'Climate Change Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Industrial Manufacturer',
        llm: { model: 'gpt-4o' },
        role: 'heavy industry',
        description: 'Represents energy-intensive manufacturing',
        backstory: 'Steel plant owner facing emission reduction mandates',
      },
      {
        id: uuidv4(),
        name: 'Environmental Regulator',
        llm: { model: 'gpt-4o' },
        role: 'policy enforcer',
        description: 'Implements and monitors carbon tax compliance',
        backstory: 'Climate scientist turned policy maker',
      },
      {
        id: uuidv4(),
        name: 'Green Tech Innovator',
        llm: { model: 'gpt-4o' },
        role: 'solution provider',
        description: 'Offers carbon reduction technologies',
        backstory: 'Clean tech entrepreneur seeing opportunity in regulations',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'International Climate Cooperation',
    description: 'Simulation of nations negotiating climate commitments',
    task: 'Model international cooperation on emission reduction targets',
    created_at: '2024-04-22T08:00:00.000Z',
    updated_at: '2024-04-22T18:00:00.000Z',
    project_name: 'Climate Change Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Developed Nation',
        llm: { model: 'gpt-4o' },
        role: 'wealthy emitter',
        description: 'High historical emissions seeking fair transition',
        backstory: 'G7 nation balancing climate action with economic growth',
      },
      {
        id: uuidv4(),
        name: 'Developing Nation',
        llm: { model: 'gpt-4o' },
        role: 'growth seeker',
        description: 'Needs development while managing emissions',
        backstory: 'Emerging economy demanding climate justice and support',
      },
      {
        id: uuidv4(),
        name: 'Island Nation',
        llm: { model: 'gpt-4o' },
        role: 'vulnerable state',
        description: 'Faces existential threat from climate change',
        backstory: 'Small island state fighting for survival',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Corporate Sustainability Transformation',
    description: 'Simulation of corporation implementing net-zero strategy',
    task: 'Transform business operations to achieve carbon neutrality',
    created_at: '2024-04-23T10:00:00.000Z',
    updated_at: '2024-04-23T17:00:00.000Z',
    project_name: 'Climate Change Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Chief Sustainability Officer',
        llm: { model: 'gpt-4o' },
        role: 'change leader',
        description: 'Drives sustainability transformation',
        backstory: 'Former NGO leader now in corporate sustainability',
      },
      {
        id: uuidv4(),
        name: 'Operations Director',
        llm: { model: 'gpt-4o' },
        role: 'pragmatist',
        description: 'Balances sustainability with operational efficiency',
        backstory: 'Veteran operator skeptical of green initiatives impact',
      },
      {
        id: uuidv4(),
        name: 'Investor Relations',
        llm: { model: 'gpt-4o' },
        role: 'market interface',
        description: 'Manages ESG investor expectations',
        backstory: 'IR head facing pressure from climate-focused funds',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Circular Economy Implementation',
    description: 'Simulation of transitioning to circular economy model',
    task: 'Design closed-loop systems to eliminate waste',
    created_at: '2024-04-24T11:00:00.000Z',
    updated_at: '2024-04-24T16:00:00.000Z',
    project_name: 'Climate Change Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Product Designer',
        llm: { model: 'gpt-4o' },
        role: 'circular designer',
        description: 'Designs products for reuse and recycling',
        backstory: 'Industrial designer passionate about cradle-to-cradle design',
      },
      {
        id: uuidv4(),
        name: 'Waste Manager',
        llm: { model: 'gpt-4o' },
        role: 'resource recovery',
        description: 'Transforms waste streams into resources',
        backstory: 'Recycling industry veteran seeing waste as opportunity',
      },
    ],
  },
]
