import { randomUUID as uuidv4 } from 'crypto'

export const simulations = [
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Weekend Planning',
    description: 'Simulation to understand how friends plan weekend activities together',
    task: 'Analyze group decision-making patterns for weekend activities',
    created_at: '2024-07-20T10:00:00.000Z',
    updated_at: '2024-07-20T10:30:00.000Z',
    project_name: 'Friends Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Sarah',
        llm: { model: 'gpt-4o' },
        role: 'social organizer',
        description: 'Enthusiastic friend who loves planning group activities',
        backstory:
          'A 28-year-old marketing professional who thrives on bringing friends together. Known for her creativity and ability to find activities that everyone enjoys.',
      },
      {
        id: uuidv4(),
        name: 'Mike',
        llm: { model: 'gpt-4o' },
        role: 'practical planner',
        description: 'Logical friend who focuses on logistics and feasibility',
        backstory:
          "A 30-year-old engineer who approaches weekend planning with systematic thinking. He's the friend who checks weather forecasts and considers travel times.",
      },
      {
        id: uuidv4(),
        name: 'Emma',
        llm: { model: 'gpt-4o' },
        role: 'budget conscious friend',
        description: 'Cost-aware friend who suggests affordable alternatives',
        backstory:
          'A 26-year-old teacher who loves spending time with friends but is mindful of expenses.',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Vacation Planning',
    description: 'Simulation to understand how couples plan vacation activities together',
    task: 'Analyze couple decision-making patterns for vacation planning',
    created_at: '2024-07-20T11:00:00.000Z',
    updated_at: '2024-07-20T11:30:00.000Z',
    project_name: 'Couple Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Ana',
        llm: { model: 'gpt-4o' },
        role: 'adventure seeker',
        description: 'Enthusiastic partner who loves outdoor activities and mountain adventures',
        backstory:
          "A 29-year-old environmental scientist who finds peace in nature and loves challenging hikes. She's always looking for the next adventure and enjoys discovering new places.",
      },
      {
        id: uuidv4(),
        name: 'John',
        llm: { model: 'gpt-4o' },
        role: 'culture enthusiast',
        description: 'Partner who enjoys cultural experiences and city exploration',
        backstory:
          'A 31-year-old architect who appreciates both modern and historical architecture. He loves exploring cities, trying local cuisine, and experiencing different cultures through travel.',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Business Strategy',
    description: 'Simulation to understand how business teams make strategic decisions',
    task: 'Analyze team decision-making patterns for business strategy',
    created_at: '2024-07-20T12:00:00.000Z',
    updated_at: '2024-07-20T12:30:00.000Z',
    project_name: 'Business Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'CEO',
        llm: { model: 'gpt-4o' },
        role: 'strategic leader',
        description: 'Chief Executive Officer who makes final strategic decisions',
        backstory:
          'A 45-year-old experienced executive with 20+ years in the industry. Known for making bold decisions and leading companies through challenging times.',
      },
      {
        id: uuidv4(),
        name: 'CFO',
        llm: { model: 'gpt-4o' },
        role: 'financial advisor',
        description: 'Chief Financial Officer who provides financial analysis and advice',
        backstory:
          'A 42-year-old finance professional with strong analytical skills. Always considers the financial implications of strategic decisions.',
      },
      {
        id: uuidv4(),
        name: 'CTO',
        llm: { model: 'gpt-4o' },
        role: 'technology expert',
        description:
          'Chief Technology Officer who provides technology insights and recommendations',
        backstory:
          'A 38-year-old technology leader with expertise in emerging technologies. Focuses on how technology can drive business growth and innovation.',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Gym Buddy Motivation',
    description: 'Simulation to study how gym buddies influence each other\'s workout consistency',
    task: 'Analyze the impact of social support on fitness motivation',
    created_at: '2024-08-01T18:00:00.000Z',
    updated_at: '2024-08-01T18:40:00.000Z',
    project_name: 'Friends Dynamics',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Alex',
        llm: { model: 'gpt-4o' },
        role: 'motivated gym buddy',
        description: 'Highly motivated fitness enthusiast who encourages their workout partner',
        backstory:
          'A 29-year-old software developer who discovered fitness three years ago and never looked back. Alex wakes up at 6 AM every day, has a detailed workout plan, and genuinely gets excited about helping others reach their fitness goals. They believe consistency is key and always shows up, even on tough days.',
      },
      {
        id: uuidv4(),
        name: 'Jordan',
        llm: { model: 'gpt-4o' },
        role: 'inconsistent gym buddy',
        description: 'Well-intentioned but struggling with workout consistency',
        backstory:
          'A 27-year-old graphic designer who wants to be fit but struggles with motivation and consistency. Jordan has good intentions and enjoys working out when they get started, but often finds excuses to skip sessions. They rely heavily on Alex\'s encouragement and feel guilty when they let their gym buddy down.',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Green Energy Adoption Rates',
    description: 'Simulation to analyze factors affecting green energy adoption',
    task: 'Study the impact of various factors on renewable energy adoption',
    created_at: '2024-04-20T08:00:00.000Z',
    updated_at: '2024-04-20T14:00:00.000Z',
    project_name: 'Climate Change Strategy',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Market Analyst',
        llm: { model: 'gpt-4o' },
        role: 'market analyst',
        description: 'Analyzes market conditions and consumer behavior',
        backstory: 'Expert in energy markets and consumer adoption patterns',
      },
      {
        id: uuidv4(),
        name: 'Policy Impact Specialist',
        llm: { model: 'gpt-4o' },
        role: 'policy specialist',
        description: 'Evaluates impact of policies on adoption rates',
        backstory: 'Specializes in energy policy analysis and implementation',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Influencer vs. Traditional Ads',
    description: 'Simulation to compare the effectiveness of influencer marketing versus traditional advertising',
    task: 'Analyze the impact of different marketing approaches on consumer behavior',
    created_at: '2024-05-10T10:00:00.000Z',
    updated_at: '2024-05-10T15:00:00.000Z',
    project_name: 'Marketing Campaign Effectiveness',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Influencer Specialist',
        llm: { model: 'gpt-4o' },
        role: 'influencer specialist',
        description: 'Designs influencer campaigns',
        backstory: 'Expert in social media marketing',
      },
      {
        id: uuidv4(),
        name: 'Traditional Ads Specialist',
        llm: { model: 'gpt-4o' },
        role: 'ads specialist',
        description: 'Designs traditional ad campaigns',
        backstory: 'Experienced in TV and print advertising',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Coalition Building and Policy Trade-offs',
    description: 'Simulation to analyze how political coalitions form and make policy decisions',
    task: 'Study the dynamics of coalition formation and policy negotiation',
    created_at: '2024-06-15T09:00:00.000Z',
    updated_at: '2024-06-15T14:00:00.000Z',
    project_name: 'Political Negotiation',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Party Leader',
        llm: { model: 'gpt-4o' },
        role: 'party leader',
        description: 'Leads a political party',
        backstory: 'Experienced negotiator',
      },
      {
        id: uuidv4(),
        name: 'Policy Analyst',
        llm: { model: 'gpt-4o' },
        role: 'policy analyst',
        description: 'Analyzes policy trade-offs',
        backstory: 'Expert in public policy',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Product Launch Timing',
    description: 'Simulation to determine optimal timing for launching a new product.',
    task: 'Analyze market conditions and competitor actions to select launch date.',
    created_at: '2024-09-10T11:00:00.000Z',
    updated_at: '2024-09-10T18:00:00.000Z',
    project_name: 'Startup Decision Making',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Market Analyst',
        llm: { model: 'gpt-4o' },
        role: 'market analyst',
        description: 'Analyzes market trends',
        backstory: 'Expert in product launches',
      },
      {
        id: uuidv4(),
        name: 'Competitor Analyst',
        llm: { model: 'gpt-4o' },
        role: 'competitor analyst',
        description: 'Tracks competitor activities',
        backstory: 'Experienced in competitive analysis',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'verified',
    name: 'Breaking Social Media Addiction',
    description: 'Simulation to study methods for overcoming social media addiction',
    task: 'Analyze the effectiveness of different addiction intervention strategies',
    created_at: '2024-05-25T11:00:00.000Z',
    updated_at: '2024-05-25T17:00:00.000Z',
    project_name: 'Digital Addiction',
    total_runs: 1,
    orchestrator: {
      id: uuidv4(),
      name: 'orchestrator',
      llm: { model: 'gpt-4o' },
    },
    evaluator: {
      id: uuidv4(),
      name: 'evaluator',
      llm: { model: 'gpt-4o' },
    },
    planner: {
      id: uuidv4(),
      name: 'planner',
      llm: { model: 'gpt-4o' },
    },
    reporter: {
      id: uuidv4(),
      name: 'reporter',
      llm: { model: 'gpt-4o' },
    },
    agents: [
      {
        id: uuidv4(),
        name: 'Maya Patel',
        llm: { model: 'gpt-4o' },
        role: 'recovering user',
        description: 'A person actively working to reduce their social media usage and break addictive patterns',
        backstory:
          'A 26-year-old marketing professional who realized her Instagram and TikTok use was affecting her sleep, work focus, and real-world relationships',
      },
      {
        id: uuidv4(),
        name: 'Jake Anderson',
        llm: { model: 'gpt-4o' },
        role: 'supportive friend',
        description: 'A friend who provides accountability and alternative activities for someone reducing social media use',
        backstory:
          'A 28-year-old outdoor enthusiast who successfully reduced his own social media use and now helps friends find offline activities and hobbies',
      },
    ],
  },
]
